service: ssrserverless-angular

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 30
  stage: production
  region: us-east-2

package:
  patterns:
   - src/**
   - node_modules/**
   - e2e/**
   - coverage/**
   ##- '!src/assets/**'
   - '!node_modules/aws-serverless-express/**'
   - '!node_modules/binary-case/**'
   - '!node_modules/type-is/**'
   - '!node_modules/media-typer/**'
   - '!node_modules/mime-types/**'
   - '!node_modules/mime-db/**'

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.ssrserverless
    events:
      - http: ANY /